name: Keep Render Awake

on:
  schedule:
    - cron: "*/8 * * * *" 
    - cron: "*/8 * * * *" 
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render API
          run: |
          echo "warming server..."
          curl -s https://be-second-hand-market.onrender.com/health