name: Warm Render Server

on:
  schedule:
    - cron: "*/8 * * * *"
    - cron: "*/9 * * * *"

jobs:
  warm:
    runs-on: ubuntu-latest

    steps:
      - name: Warm server
        run: |
          curl -H "User-Agent: Mozilla/5.0" https://be-second-hand-market.onrender.com/health